<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (game+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT game (description, year?, manufacturer, biosset*, rom*, disk*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, category*, adjuster*, driver?, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game sourcefile CDATA #IMPLIED>
		<!ATTLIST game isbios (yes|no) "no">
		<!ATTLIST game ismechanical (yes|no) "no">
		<!ATTLIST game runnable (yes|no) "yes">
		<!ATTLIST game cloneof CDATA #IMPLIED>
		<!ATTLIST game romof CDATA #IMPLIED>
		<!ATTLIST game sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display type (raster|vector|lcd|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #REQUIRED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT confsetting EMPTY>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT category (item*)>
			<!ATTLIST category name CDATA #REQUIRED>
			<!ELEMENT item EMPTY>
				<!ATTLIST item name CDATA #REQUIRED>
				<!ATTLIST item default (yes|no) "no">
		<!ELEMENT adjuster EMPTY>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.143 (Jun 28 2011)" debug="no" mameconfig="10">
	<game name="005" sourcefile="segag80r.c">
		<description>005</description>
		<year>1981</year>
		<manufacturer>Sega</manufacturer>
		<rom name="1346b.cpu-u25" size="2048" crc="8e68533e" sha1="a257c556d31691068ed5c991f1fb2b51da4826db" region="maincpu" offset="0"/>
		<rom name="5092.prom-u1" size="2048" crc="29e10a81" sha1="c4b4e6c75bcf276e53f39a456d8d633c83dcf485" region="maincpu" offset="800"/>
		<rom name="5093.prom-u2" size="2048" crc="e1edc3df" sha1="4f593546bbb0f50850dc6286cb514af6831c27a7" region="maincpu" offset="1000"/>
		<rom name="5094.prom-u3" size="2048" crc="995773bb" sha1="98dd826527853bc031edfb9a821778cc3e906150" region="maincpu" offset="1800"/>
		<rom name="5095.prom-u4" size="2048" crc="f887f575" sha1="de96573a91b60b090b1f441f1410ecad63c9467c" region="maincpu" offset="2000"/>
		<rom name="5096.prom-u5" size="2048" crc="5545241e" sha1="ee504ccaab469100137717341a1b461175ff792d" region="maincpu" offset="2800"/>
		<rom name="5097.prom-u6" size="2048" crc="428edb54" sha1="4f3df6017068d939014a8f638f28e3228acb7add" region="maincpu" offset="3000"/>
		<rom name="5098.prom-u7" size="2048" crc="5bcb9d63" sha1="c0c91bc9f75ad88a6e15c554a980d5c075725fe8" region="maincpu" offset="3800"/>
		<rom name="5099.prom-u8" size="2048" crc="0ea24ba3" sha1="95a30c9b63ef1c346df0da71af3fdecd1a75cb8f" region="maincpu" offset="4000"/>
		<rom name="5100.prom-u9" size="2048" crc="a79af131" sha1="0ba34130174e196015bc9b9c135c420209dfd524" region="maincpu" offset="4800"/>
		<rom name="5101.prom-u10" size="2048" crc="8a1cdae0" sha1="f7c617f9bdb7818e6069a981d0c8820deade134c" region="maincpu" offset="5000"/>
		<rom name="5102.prom-u11" size="2048" crc="70826a15" sha1="a86322d0e8a88534e9b78dcde42ae4c441276913" region="maincpu" offset="5800"/>
		<rom name="5103.prom-u12" size="2048" crc="7f80c5b0" sha1="00748cd5fc7f75fdca194e748524d406c006296d" region="maincpu" offset="6000"/>
		<rom name="5104.prom-u13" size="2048" crc="0140930e" sha1="f8ef894c46d3663bd89d2d817675a67075d3e0d6" region="maincpu" offset="6800"/>
		<rom name="5105.prom-u14" size="2048" crc="17807a05" sha1="bd99f5beab0155f6e4d2fab2fa5f4e147c5730d5" region="maincpu" offset="7000"/>
		<rom name="5106.prom-u15" size="2048" crc="c7cdfa9d" sha1="6ab7adc60ac7bb53a7175e8de51924008737c9ac" region="maincpu" offset="7800"/>
		<rom name="5107.prom-u16" size="2048" crc="95f8a2e6" sha1="89c92e000b3e1630380db779370cf9f5b13e5719" region="maincpu" offset="8000"/>
		<rom name="5108.prom-u17" size="2048" crc="d371cacd" sha1="8f2cdcc0b4e3b77e0958d257e37accefc5749cde" region="maincpu" offset="8800"/>
		<rom name="5109.prom-u18" size="2048" crc="48a20617" sha1="5b4bc3beda0404ff0a61bb42751b87f71817f363" region="maincpu" offset="9000"/>
		<rom name="5110.prom-u19" size="2048" crc="7d26111a" sha1="a6d3652ae606a5b75026e524c9d6aaa78300741e" region="maincpu" offset="9800"/>
		<rom name="5111.prom-u20" size="2048" crc="a888e175" sha1="4c0af94441bf51dfc852372a5b90d0830df81363" region="maincpu" offset="a000"/>
		<rom name="epr-1286.sound-16" size="2048" crc="fbe0d501" sha1="bfa277689790f835d8a43be4beee0581e1096bcc" region="005" offset="0"/>
		<rom name="6331.sound-u8" size="32" crc="1d298cb0" sha1="bb0bb62365402543e3154b9a77be9c75010e6abc" region="proms" status="baddump" offset="0"/>
		<sample name="lexplode.wav"/>
		<sample name="sexplode.wav"/>
		<sample name="dropbomb.wav"/>
		<sample name="shoot.wav"/>
		<sample name="missile.wav"/>
		<sample name="heilcopt.wav"/>
		<sample name="whistle.wav"/>
		<chip type="cpu" tag="maincpu" name="Z80" clock="3867000"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="samples" name="Samples"/>
		<chip type="audio" tag="005" name="005 Custom"/>
		<display type="raster" rotate="270" width="256" height="224" refresh="59.998138" pixclock="5156000" htotal="328" hbend="0" hbstart="256" vtotal="262" vbend="0" vbstart="224" />
		<sound channels="1"/>
		<input players="2" buttons="1" coins="2" service="yes">
			<control type="joy4way"/>
		</input>
		<dipswitch name="Lives" tag="D3D2" mask="3">
			<dipvalue name="3" value="0" default="yes"/>
			<dipvalue name="4" value="2"/>
			<dipvalue name="5" value="1"/>
			<dipvalue name="6" value="3"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="D3D2" mask="4">
			<dipvalue name="Upright" value="4" default="yes"/>
			<dipvalue name="Cocktail" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="8">
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="16">
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="32">
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="D1D0" mask="15">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="9"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="10"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="1 Coin/1 Credit" value="3" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="11"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="12"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="13"/>
			<dipvalue name="1 Coin/2 Credits" value="4"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="15"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="14"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="6"/>
			<dipvalue name="1 Coin/5 Credits" value="7"/>
			<dipvalue name="1 Coin/6 Credits" value="8"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="D1D0" mask="240">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="16"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="144"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="160"/>
			<dipvalue name="2 Coins/1 Credit" value="32"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="176"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="192"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="208"/>
			<dipvalue name="1 Coin/2 Credits" value="64"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="240"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="224"/>
			<dipvalue name="1 Coin/3 Credits" value="80"/>
			<dipvalue name="1 Coin/4 Credits" value="96"/>
			<dipvalue name="1 Coin/5 Credits" value="112"/>
			<dipvalue name="1 Coin/6 Credits" value="128"/>
		</dipswitch>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="64"/>
	</game>
	<game name="10yard" sourcefile="m58.c">
		<description>10-Yard Fight (World, set 1)</description>
		<year>1983</year>
		<manufacturer>Irem</manufacturer>
		<rom name="yf-a-3p-b" size="8192" crc="2e205ec2" sha1="fcfa08f45423b35f2c99d4e6b5474ab1b3a84fec" region="maincpu" offset="0"/>
		<rom name="yf-a-3n-b" size="8192" crc="82fcd980" sha1="7846705b29961cb95ee1571ee7e16baceea522d4" region="maincpu" offset="2000"/>
		<rom name="yf-a-3m-b" size="8192" crc="a8d5c311" sha1="28edb5cfd943a2262d7e37ef9a7245f7017cbc51" region="maincpu" offset="4000"/>
		<rom name="yf-s.3b" size="8192" crc="0392a60c" sha1="68030504eafc58db250099edd3c3323bdb9eff6b" region="iremsound" offset="8000"/>
		<rom name="yf-s.1b" size="8192" crc="6588f41a" sha1="209305efc68171886427216b9a0b37333f40daa8" region="iremsound" offset="a000"/>
		<rom name="yf-s.3a" size="8192" crc="bd054e44" sha1="f10c32c70d60680229fc0891d0e1308015fa69d6" region="iremsound" offset="c000"/>
		<rom name="yf-s.1a" size="8192" crc="2490d4c3" sha1="e4da7b01e8ad075b7e3c8beb6668faff72db9aa2" region="iremsound" offset="e000"/>
		<rom name="yf-a.3e" size="8192" crc="77e9e9cc" sha1="90b0226fc125713dbee2804aeceeb5aa2c8e275e" region="gfx1" offset="0"/>
		<rom name="yf-a.3d" size="8192" crc="854d5ff4" sha1="9ba09bfabf159facb57faecfe73a6258fa48d152" region="gfx1" offset="2000"/>
		<rom name="yf-a.3c" size="8192" crc="0cd8ffad" sha1="bd1262de3823c34f7394b718477fb5bc58a6e293" region="gfx1" offset="4000"/>
		<rom name="yf-b.5b" size="8192" crc="1299ae30" sha1="07d47f827d8bc78a41011ec02ab64036fb8a7a18" region="gfx2" offset="0"/>
		<rom name="yf-b.5c" size="8192" crc="8708b888" sha1="8c4f305a339f23ec8ed40dfd72fac0f62ee65378" region="gfx2" offset="2000"/>
		<rom name="yf-b.5f" size="8192" crc="d9bb8ab8" sha1="1325308b4c85355298fec4aa3e5fec1b4b13ad86" region="gfx2" offset="4000"/>
		<rom name="yf-b.5e" size="8192" crc="47077e8d" sha1="5f78b15fb360e9926ef11841d5d86f2bd9af04d1" region="gfx2" offset="6000"/>
		<rom name="yf-b.5j" size="8192" crc="713ef31f" sha1="b48df9ed4f26fded3c7eaac3a52b580b2dd60477" region="gfx2" offset="8000"/>
		<rom name="yf-b.5k" size="8192" crc="f49651cc" sha1="5b87d7360bcd5883ec265b2a01a3e02e10a85345" region="gfx2" offset="a000"/>
		<rom name="yard.1c" size="256" crc="08fa5103" sha1="98af48dafbbaa42f58232bf74ccbf5da41723e71" region="proms" offset="0"/>
		<rom name="yard.1d" size="256" crc="7c04994c" sha1="790bf1616335b9df4943cffcafa48d8e8aee009e" region="proms" offset="100"/>
		<rom name="yard.1f" size="32" crc="b8554da5" sha1="963ca815b5f791b8a7b0937a5d392d5203049eb3" region="proms" offset="200"/>
		<rom name="yard.2h" size="256" crc="e1cdfb06" sha1="a8cc3456cfc272e3faac80370b2298d8e1f8c2fe" region="proms" offset="220"/>
		<rom name="yard.2n" size="256" crc="cd85b646" sha1="5268db705006058eec308afe474f4df3c15465bb" region="proms" offset="320"/>
		<rom name="yard.2m" size="256" crc="45384397" sha1="e4c662ee81aef63efd8b4a45f85c4a78dc2d419e" region="proms" offset="420"/>
		<chip type="cpu" tag="maincpu" name="Z80" clock="3072000"/>
		<chip type="cpu" tag="iremsound" name="M6803" clock="3579545"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="irem_audio" name="Irem Audio"/>
		<chip type="audio" tag="ay1" name="AY-3-8910A" clock="894886"/>
		<chip type="audio" tag="ay2" name="AY-3-8910A" clock="894886"/>
		<chip type="audio" tag="msm1" name="MSM5205" clock="384000"/>
		<chip type="audio" tag="msm2" name="MSM5205" clock="384000"/>
		<display type="raster" rotate="0" width="256" height="224" refresh="56.737589" pixclock="6144000" htotal="384" hbend="0" hbstart="256" vtotal="282" vbend="42" vbstart="266" />
		<sound channels="1"/>
		<input players="2" buttons="2" coins="2">
			<control type="joy8way"/>
		</input>
		<dipswitch name="Flip Screen" tag="DSW2" mask="1">
			<dipvalue name="Off" value="1" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="DSW2" mask="2">
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="2"/>
		</dipswitch>
		<dipswitch name="Coin Mode" tag="DSW2" mask="4">
			<dipvalue name="Mode 1" value="4" default="yes"/>
			<dipvalue name="Mode 2" value="0"/>
		</dipswitch>
		<dipswitch name="Slow Motion (Cheat)" tag="DSW2" mask="8">
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Stop Mode (Cheat)" tag="DSW2" mask="16">
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Level Select (Cheat)" tag="DSW2" mask="32">
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Invulnerability (Cheat)" tag="DSW2" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSW2" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSW1" mask="1">
			<dipvalue name="Off" value="1" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSW1" mask="2">
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Time Reduced by Ball Dead" tag="DSW1" mask="12">
			<dipvalue name="Normal" value="12" default="yes"/>
			<dipvalue name="x1.3" value="8"/>
			<dipvalue name="x1.5" value="4"/>
			<dipvalue name="x1.8" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSW1" mask="48">
			<dipvalue name="3 Coins/1 Credit" value="16"/>
			<dipvalue name="2 Coins/1 Credit" value="32"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="Free Play" value="0"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSW1" mask="192">
			<dipvalue name="1 Coin/2 Credits" value="192" default="yes"/>
			<dipvalue name="1 Coin/3 Credits" value="128"/>
			<dipvalue name="1 Coin/5 Credits" value="64"/>
			<dipvalue name="1 Coin/6 Credits" value="0"/>
		</dipswitch>
		<dipswitch name="Coinage" tag="DSW1" mask="240">
			<dipvalue name="7 Coins/1 Credit" value="144"/>
			<dipvalue name="6 Coins/1 Credit" value="160"/>
			<dipvalue name="5 Coins/1 Credit" value="176"/>
			<dipvalue name="4 Coins/1 Credit" value="192"/>
			<dipvalue name="3 Coins/1 Credit" value="208"/>
			<dipvalue name="2 Coins/1 Credit" value="224"/>
			<dipvalue name="1 Coin/1 Credit" value="240" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="112"/>
			<dipvalue name="1 Coin/3 Credits" value="96"/>
			<dipvalue name="1 Coin/4 Credits" value="80"/>
			<dipvalue name="1 Coin/5 Credits" value="64"/>
			<dipvalue name="1 Coin/6 Credits" value="48"/>
			<dipvalue name="1 Coin/7 Credits" value="32"/>
			<dipvalue name="1 Coin/8 Credits" value="16"/>
			<dipvalue name="Free Play" value="0"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="768"/>
	</game>
	<game name="nightstrj" sourcefile="taito_z.c" cloneof="nightstr" romof="nightstr">
		<description>Night Striker (Japan)</description>
		<year>1989</year>
		<manufacturer>Taito Corporation</manufacturer>
		<rom name="b91-45.bin" merge="b91-45.bin" size="131072" crc="7ad63421" sha1="4ecfc3c8cd691d878e5d9212ccff0d225bb06bd9" region="maincpu" offset="0"/>
		<rom name="b91-44.bin" merge="b91-44.bin" size="131072" crc="4bc30adf" sha1="531d6ee9c8ff0d4ed07c15465ec7cb78cf976115" region="maincpu" offset="1"/>
		<rom name="b91-43.bin" merge="b91-43.bin" size="131072" crc="3e6f727a" sha1="ae837131a4c0c9bc5deba155c2a5b7ae72f1d070" region="maincpu" offset="40000"/>
		<rom name="b91-42.bin" size="131072" crc="7179ef2f" sha1="4c45f0c4dfcf16665d7eca4fdcd6a959d9b6fc01" region="maincpu" offset="40001"/>
		<rom name="b91-39.bin" merge="b91-39.bin" size="131072" crc="725b23ae" sha1="d4b4335863d32b9a81f7461240e960bf345c9835" region="sub" offset="0"/>
		<rom name="b91-40.bin" merge="b91-40.bin" size="131072" crc="81fb364d" sha1="f02733509039cde2c1de616e0a7969e31de1007a" region="sub" offset="1"/>
		<rom name="b91-41.bin" merge="b91-41.bin" size="131072" crc="2694bb42" sha1="ee770472655ac0ef55eeff04037457dbf6744e4f" region="audiocpu" offset="0"/>
		<rom name="b91-11.bin" merge="b91-11.bin" size="524288" crc="fff8ce31" sha1="fc729de92937a805d79379228d7a30041594c0df" region="gfx1" offset="0"/>
		<rom name="b91-04.bin" merge="b91-04.bin" size="524288" crc="8ca1970d" sha1="d8504298a38a95f1d8f3a2fba479ec75fe4d5de7" region="gfx2" offset="0"/>
		<rom name="b91-03.bin" merge="b91-03.bin" size="524288" crc="cd5fed39" sha1="c16c67cc998889288e6e96535fd8e61afc93bc78" region="gfx2" offset="1"/>
		<rom name="b91-02.bin" merge="b91-02.bin" size="524288" crc="457c64b8" sha1="443f13d56d53ca6a7750ec974da675bad3f34a38" region="gfx2" offset="2"/>
		<rom name="b91-01.bin" merge="b91-01.bin" size="524288" crc="3731d94f" sha1="2978d3eb1f44595681e84f3aa8dc03d34a191455" region="gfx2" offset="3"/>
		<rom name="b91-10.bin" merge="b91-10.bin" size="524288" crc="1d8f05b4" sha1="04caa6a0887b90860c426a973dc3c3270e996818" region="gfx3" offset="0"/>
		<rom name="b91-08.bin" merge="b91-08.bin" size="524288" crc="66f35c34" sha1="9040390fa9c626a54076a9461e0e198f059e2cb1" region="gfx4" offset="0"/>
		<rom name="b91-07.bin" merge="b91-07.bin" size="524288" crc="4d8ec6cf" sha1="2b7c10b459dc45313c4c90899a73c42c55b6c5c9" region="gfx4" offset="1"/>
		<rom name="b91-06.bin" merge="b91-06.bin" size="524288" crc="a34dc839" sha1="e1fcb763dbc562a62e862297458bde66d691606c" region="gfx4" offset="2"/>
		<rom name="b91-05.bin" merge="b91-05.bin" size="524288" crc="5e72ac90" sha1="c28c2718e873be5a254992ef8db256a394ca03ff" region="gfx4" offset="3"/>
		<rom name="b91-09.bin" merge="b91-09.bin" size="524288" crc="5f247ca2" sha1="3b89e5d035f27f62a14c5c7a976c804f9bb5c04d" region="user1" offset="0"/>
		<rom name="b91-13.bin" merge="b91-13.bin" size="524288" crc="8c7bf0f5" sha1="6e18531991225c24a9722c9fbe1af6ae6e9b866b" region="ymsnd" offset="0"/>
		<rom name="b91-12.bin" merge="b91-12.bin" size="524288" crc="da77c7af" sha1="49662a69b83739e2e0209cabff83995a951383f4" region="ymsnd" offset="80000"/>
		<rom name="b91-14.bin" merge="b91-14.bin" size="524288" crc="6bc314d3" sha1="ae3e9c6b853bab4ec81a6bd951b39a4bc883f456" region="ymsnd.deltat" offset="0"/>
		<rom name="b91-26.bin" merge="b91-26.bin" size="1024" crc="77682a4f" sha1="da2b3143f1c8688a22d8ec47bbb73b2f2e578480" region="user2" offset="0"/>
		<rom name="b91-27.bin" merge="b91-27.bin" size="1024" crc="a3f8490d" sha1="349b8c9ba914603f72f800a3fc8e8277d756deb1" region="user2" offset="0"/>
		<rom name="b91-28.bin" merge="b91-28.bin" size="1024" crc="fa2f840e" sha1="dd61ee6833bd43bbf619d36ec46f2bfa00880f40" region="user2" offset="0"/>
		<rom name="b91-29.bin" merge="b91-29.bin" size="8192" crc="ad685be8" sha1="e7681d76fa216c124c54544393c4f6a08fd7d74d" region="user2" offset="0"/>
		<rom name="b91-30.bin" merge="b91-30.bin" size="65536" crc="30cc1f79" sha1="3b0e3e6e8bce7a7d04a5b0103e2ce4e18e52a68e" region="user2" offset="0"/>
		<rom name="b91-31.bin" merge="b91-31.bin" size="65536" crc="c189781c" sha1="af3904ce51f715970965d110313491dbacf188b8" region="user2" offset="0"/>
		<rom name="b91-32.bin" merge="b91-32.bin" size="256" crc="fbf81f30" sha1="c868452c334792345dcced075f6df69cff9e31ca" region="user2" offset="0"/>
		<rom name="b91-33.bin" merge="b91-33.bin" size="256" crc="89719d17" sha1="50181b8172b0fc08b149db18caf10659be9c517f" region="user2" offset="0"/>
		<chip type="cpu" tag="maincpu" name="68000" clock="12000000"/>
		<chip type="cpu" tag="audiocpu" name="Z80" clock="4000000"/>
		<chip type="cpu" tag="sub" name="68000" clock="12000000"/>
		<chip type="audio" tag="front" name="Speaker"/>
		<chip type="audio" tag="rear" name="Speaker"/>
		<chip type="audio" tag="subwoofer" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2610" clock="8000000"/>
		<chip type="audio" tag="2610.1.r" name="Volume Filter"/>
		<chip type="audio" tag="2610.1.l" name="Volume Filter"/>
		<chip type="audio" tag="2610.2.r" name="Volume Filter"/>
		<chip type="audio" tag="2610.2.l" name="Volume Filter"/>
		<display type="raster" rotate="0" width="320" height="240" refresh="60.000000" />
		<sound channels="3"/>
		<input players="1" buttons="2" coins="2" tilt="yes">
			<control type="joy8way"/>
			<control type="stick" minimum="0" maximum="255" sensitivity="60" keydelta="15" reverse="yes"/>
		</input>
		<dipswitch name="Cabinet" tag="DSWA" mask="1">
			<dipvalue name="Cockpit" value="1"/>
			<dipvalue name="Upright" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWA" mask="2">
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSWA" mask="4">
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWA" mask="8">
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSWA" mask="48">
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="32"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="192">
			<dipvalue name="2 Coins/1 Credit" value="64"/>
			<dipvalue name="1 Coin/1 Credit" value="192" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="128"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="3">
			<dipvalue name="Easy" value="2"/>
			<dipvalue name="Medium" value="3" default="yes"/>
			<dipvalue name="Hard" value="1"/>
			<dipvalue name="Hardest" value="0"/>
		</dipswitch>
		<dipswitch name="Bonus Shields" tag="DSWB" mask="12">
			<dipvalue name="3" value="8"/>
			<dipvalue name="2" value="4"/>
			<dipvalue name="1" value="12" default="yes"/>
			<dipvalue name="None" value="0"/>
		</dipswitch>
		<dipswitch name="Shields" tag="DSWB" mask="48">
			<dipvalue name="3" value="0"/>
			<dipvalue name="4" value="16"/>
			<dipvalue name="5" value="48" default="yes"/>
			<dipvalue name="6" value="32"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWB" mask="64">
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="64" default="yes"/>
		</dipswitch>
		<dipswitch name="Trigger Turbo" tag="DSWB" mask="128">
			<dipvalue name="7 Shots / Second" value="128" default="yes"/>
			<dipvalue name="10 Shots / Second" value="0"/>
		</dipswitch>
		<dipswitch name="Adjust Stick H (VARIABLE REGISTER)" tag="X_ADJUST" mask="255">
			<dipvalue name="-80" value="0"/>
			<dipvalue name="-7F" value="1"/>
			<dipvalue name="-7E" value="2"/>
			<dipvalue name="-7D" value="3"/>
			<dipvalue name="-7C" value="4"/>
			<dipvalue name="-7B" value="5"/>
			<dipvalue name="-7A" value="6"/>
			<dipvalue name="-79" value="7"/>
			<dipvalue name="-78" value="8"/>
			<dipvalue name="-77" value="9"/>
			<dipvalue name="-76" value="10"/>
			<dipvalue name="-75" value="11"/>
			<dipvalue name="-74" value="12"/>
			<dipvalue name="-73" value="13"/>
			<dipvalue name="-72" value="14"/>
			<dipvalue name="-71" value="15"/>
			<dipvalue name="-70" value="16"/>
			<dipvalue name="-6F" value="17"/>
			<dipvalue name="-6E" value="18"/>
			<dipvalue name="-6D" value="19"/>
			<dipvalue name="-6C" value="20"/>
			<dipvalue name="-6B" value="21"/>
			<dipvalue name="-6A" value="22"/>
			<dipvalue name="-69" value="23"/>
			<dipvalue name="-68" value="24"/>
			<dipvalue name="-67" value="25"/>
			<dipvalue name="-66" value="26"/>
			<dipvalue name="-65" value="27"/>
			<dipvalue name="-64" value="28"/>
			<dipvalue name="-63" value="29"/>
			<dipvalue name="-62" value="30"/>
			<dipvalue name="-61" value="31"/>
			<dipvalue name="-60" value="32"/>
			<dipvalue name="-5F" value="33"/>
			<dipvalue name="-5E" value="34"/>
			<dipvalue name="-5D" value="35"/>
			<dipvalue name="-5C" value="36"/>
			<dipvalue name="-5B" value="37"/>
			<dipvalue name="-5A" value="38"/>
			<dipvalue name="-59" value="39"/>
			<dipvalue name="-58" value="40"/>
			<dipvalue name="-57" value="41"/>
			<dipvalue name="-56" value="42"/>
			<dipvalue name="-55" value="43"/>
			<dipvalue name="-54" value="44"/>
			<dipvalue name="-53" value="45"/>
			<dipvalue name="-52" value="46"/>
			<dipvalue name="-51" value="47"/>
			<dipvalue name="-50" value="48"/>
			<dipvalue name="-4F" value="49"/>
			<dipvalue name="-4E" value="50"/>
			<dipvalue name="-4D" value="51"/>
			<dipvalue name="-4C" value="52"/>
			<dipvalue name="-4B" value="53"/>
			<dipvalue name="-4A" value="54"/>
			<dipvalue name="-49" value="55"/>
			<dipvalue name="-48" value="56"/>
			<dipvalue name="-47" value="57"/>
			<dipvalue name="-46" value="58"/>
			<dipvalue name="-45" value="59"/>